# Pre-processing Colonies Dataset (6 Sep2021)

* Data Pre-processing **[done]**
    * Import colonies
    * Import barrier files – reproject all to EPSG 7760
    * Check validity of all shapefiles (turn this into a function…) – also check that all points are in Delhi. (might be part of spatial index notebook and UAC deduplication)    
* Compute barrier clip for all colonies **[done]**
* Run Neighbors Algorithm **[done]**
    * bbox Neighbors algorithm
    * Should check for barriers
    * Should check for NDMC and related areas
* Additional preprocessing for colonies (turn into super function) **[done]**
    * Create index column **[done]**
    * Distance from NDMC **[done]**
    * Area of each polygon **[done]**
* Export GeoDataFrame as pickle file and ESRI Shapefiles

## Import modules and set constants

In [1]:
import os
import pickle
from importlib import reload
import pandas as pd
import geopandas as gpd
from shapely.geometry import Polygon, box
import spatial_index_utils

In [2]:
reload(spatial_index_utils)

In [3]:
# WGS 84 / Delhi
epsg_code = 7760

## Import shapefiles **[done]**

In [5]:
colony_filepath = os.path.join('shapefiles', 'Spatial_Index_GIS', 'Colony_Shapefile',
                               '6sep2021', 'uso_update_sep2021.shp')

barrier_directory = os.path.join('shapefiles', 'Barrier_Clip')

canal_filepath = os.path.join(barrier_directory, 'Canal', 'Canal.shp')
drain_filepath = os.path.join(barrier_directory, 'Drain', 'Major_Drain.shp')
railway_filepath = os.path.join(barrier_directory, 'Railway', 'Railway_Line.shp')

# boundary of Delhi
delhi_bounds_filepath = os.path.join('shapefiles', 'delhi_bounds_buffer.shp')

# Check that all filepaths exist
filepath_list = [colony_filepath, canal_filepath, drain_filepath, railway_filepath, delhi_bounds_filepath]

for filepath in filepath_list:
    if not os.path.exists(filepath):
        print('{} does not exist'.format(filepath))

In [6]:
colonies = gpd.read_file(colony_filepath)

## Inspect shapefiles for validity (`check_shapefile`) **[done]**

In [7]:
spatial_index_utils.check_shapefile(gdf=colonies, gdf_name='colonies', 
                                    geom_type='Polygon', 
                                    delhi_bounds_filepath=delhi_bounds_filepath)

colonies has duplicate rows: False
----------------------------------------------------
rows with invalid geometries

----------------------------------------------------
all geometries in colonies are of type Polygon: True
----------------------------------------------------
Rows with None value in geometry column are below
Empty GeoDataFrame
Columns: [AREA, USO_AREA_U, HOUSETAX_C, USO_FINAL, geometry, geom_type]
Index: []
----------------------------------------------------
colonies shapefile is contained within Delhi: True
----------------------------------------------------
Done with shapefile evaluation

In [ ]:
# spatial_index_utils.check_shapefile(gdf=canal, gdf_name='canal', geom_type='Line', 
#                                     delhi_bounds_filepath=delhi_bounds_filepath)

In [ ]:
# spatial_index_utils.check_shapefile(gdf=drain, gdf_name='drain', geom_type='Line', 
#                                     delhi_bounds_filepath=delhi_bounds_filepath)

In [ ]:
# spatial_index_utils.check_shapefile(gdf=railway, gdf_name='railway', geom_type='Line', 
#                                     delhi_bounds_filepath=delhi_bounds_filepath)

## Remove duplicate geometries **[done]**

In [ ]:
#canal = spatial_index_utils.remove_duplicate_geom(canal)
#drain = spatial_index_utils.remove_duplicate_geom(drain)
#railway = spatial_index_utils.remove_duplicate_geom(railway)

#with open('canal.data', 'wb') as f:
#    pickle.dump(canal, f)

#with open('drain.data', 'wb') as f:
#    pickle.dump(drain, f)

#with open('railway.data', 'wb') as f:
#    pickle.dump(railway, f)

In [8]:
colonies = spatial_index_utils.remove_duplicate_geom(colonies)

1it [00:00,  6.24it/s]

0/4357

101it [00:18,  3.84it/s]

100/4357

201it [00:43,  3.93it/s]

200/4357

300it [01:06,  4.59it/s]

300/4357

401it [01:24,  6.14it/s]

400/4357

501it [01:40,  6.21it/s]

500/4357

601it [01:56,  6.05it/s]

600/4357

701it [02:12,  5.88it/s]

700/4357

801it [02:28,  6.13it/s]

800/4357

901it [02:44,  6.31it/s]

900/4357

1001it [03:00,  6.32it/s]

1000/4357

1101it [03:16,  6.01it/s]

1100/4357

1201it [03:31,  6.97it/s]

1200/4357

1302it [03:46,  6.66it/s]

1300/4357

1401it [04:00,  6.75it/s]

1400/4357

1501it [04:16,  6.51it/s]

1500/4357

1601it [04:34,  5.46it/s]

1600/4357

1701it [04:51,  6.58it/s]

1700/4357

1801it [05:07,  5.89it/s]

1800/4357

1901it [05:24,  5.74it/s]

1900/4357

2001it [05:42,  6.29it/s]

2000/4357

2101it [06:00,  5.61it/s]

2100/4357

2201it [06:16,  6.23it/s]

2200/4357

2301it [06:33,  6.62it/s]

2300/4357

2401it [06:49,  5.33it/s]

2400/4357

2501it [07:06,  6.56it/s]

2500/4357

2601it [07:21,  6.29it/s]

2600/4357

2701it [07:36,  6.32it/s]

2700/4357

2801it [07:51,  6.74it/s]

2800/4357

2901it [08:06,  6.38it/s]

2900/4357

3001it [08:21,  6.96it/s]

3000/4357

3101it [08:35,  7.14it/s]

3100/4357

3201it [08:49,  7.35it/s]

3200/4357

3301it [09:03,  7.43it/s]

3300/4357

3401it [09:16,  6.86it/s]

3400/4357

3501it [09:30,  7.61it/s]

3500/4357

3601it [09:44,  7.62it/s]

3600/4357

3701it [09:57,  7.52it/s]

3700/4357

3801it [10:11,  7.80it/s]

3800/4357

3901it [10:24,  7.71it/s]

3900/4357

4001it [10:37,  7.63it/s]

4000/4357

4101it [10:50,  7.89it/s]

4100/4357

4201it [11:04,  7.87it/s]

4200/4357

4302it [11:17,  8.06it/s]

4300/4357

4357it [11:24,  6.36it/s]

Original number of rows is 4357:
New number of rows after deduplication is: 4357

In [9]:
len(colonies)

4357

In [10]:
colonies.to_csv("colonies_no_duplicates_6Sep2021.csv")

## Import canal, drain, and railway shapefiles

In [11]:
with open('canal.data', 'rb') as f:
    canal = pickle.load(f)

In [12]:
with open('drain.data', 'rb') as f:
    drain = pickle.load(f)

In [13]:
with open('railway.data', 'rb') as f:
    railway = pickle.load(f)

## Check CRS, reproject to EPSG:7760.

In [14]:
colonies.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [19]:
colonies = spatial_index_utils.reproject_gdf(colonies, epsg_code)

GeoDataFrame now has the following CRS:

PROJCRS["WGS 84 / Delhi",BASEGEOGCRS["WGS 84",ENSEMBLE["World Geodetic System 1984 ensemble",MEMBER["World Geodetic System 1984 (Transit)"],MEMBER["World Geodetic System 1984 (G730)"],MEMBER["World Geodetic System 1984 (G873)"],MEMBER["World Geodetic System 1984 (G1150)"],MEMBER["World Geodetic System 1984 (G1674)"],MEMBER["World Geodetic System 1984 (G1762)"],ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1]],ENSEMBLEACCURACY[2.0]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4326]],CONVERSION["Delhi NSF LCC",METHOD["Lambert Conic Conformal (2SP)",ID["EPSG",9802]],PARAMETER["Latitude of false origin",28.62510126,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8821]],PARAMETER["Longitude of false origin",77,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8822]],PARAMETER["Latitude of 1st standard parallel",28.375,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8823]],PARAMETER["Latitude of 2nd standard parallel",28.875,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8824]],PARAMETER["Easting at false origin",1000000,LENGTHUNIT["metre",1],ID["EPSG",8826]],PARAMETER["Northing at false origin",1000000,LENGTHUNIT["metre",1],ID["EPSG",8827]]],CS[Cartesian,2],AXIS["easting (X)",east,ORDER[1],LENGTHUNIT["metre",1]],AXIS["northing (Y)",north,ORDER[2],LENGTHUNIT["metre",1]],USAGE[SCOPE["NNRMS National Spatial Framework (NSF) state resource database of medium resolution earth observation imagery and mapping."],AREA["India - Delhi national capital territory."],BBOX[28.4,76.83,28.89,77.34]],ID["EPSG",7760]]

In [20]:
canal = spatial_index_utils.reproject_gdf(canal, epsg_code)

GeoDataFrame now has the following CRS:

PROJCRS["WGS 84 / Delhi",BASEGEOGCRS["WGS 84",ENSEMBLE["World Geodetic System 1984 ensemble",MEMBER["World Geodetic System 1984 (Transit)"],MEMBER["World Geodetic System 1984 (G730)"],MEMBER["World Geodetic System 1984 (G873)"],MEMBER["World Geodetic System 1984 (G1150)"],MEMBER["World Geodetic System 1984 (G1674)"],MEMBER["World Geodetic System 1984 (G1762)"],ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1]],ENSEMBLEACCURACY[2.0]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4326]],CONVERSION["Delhi NSF LCC",METHOD["Lambert Conic Conformal (2SP)",ID["EPSG",9802]],PARAMETER["Latitude of false origin",28.62510126,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8821]],PARAMETER["Longitude of false origin",77,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8822]],PARAMETER["Latitude of 1st standard parallel",28.375,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8823]],PARAMETER["Latitude of 2nd standard parallel",28.875,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8824]],PARAMETER["Easting at false origin",1000000,LENGTHUNIT["metre",1],ID["EPSG",8826]],PARAMETER["Northing at false origin",1000000,LENGTHUNIT["metre",1],ID["EPSG",8827]]],CS[Cartesian,2],AXIS["easting (X)",east,ORDER[1],LENGTHUNIT["metre",1]],AXIS["northing (Y)",north,ORDER[2],LENGTHUNIT["metre",1]],USAGE[SCOPE["NNRMS National Spatial Framework (NSF) state resource database of medium resolution earth observation imagery and mapping."],AREA["India - Delhi national capital territory."],BBOX[28.4,76.83,28.89,77.34]],ID["EPSG",7760]]

In [21]:
drain = spatial_index_utils.reproject_gdf(drain, epsg_code)

GeoDataFrame now has the following CRS:

PROJCRS["WGS 84 / Delhi",BASEGEOGCRS["WGS 84",ENSEMBLE["World Geodetic System 1984 ensemble",MEMBER["World Geodetic System 1984 (Transit)"],MEMBER["World Geodetic System 1984 (G730)"],MEMBER["World Geodetic System 1984 (G873)"],MEMBER["World Geodetic System 1984 (G1150)"],MEMBER["World Geodetic System 1984 (G1674)"],MEMBER["World Geodetic System 1984 (G1762)"],ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1]],ENSEMBLEACCURACY[2.0]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4326]],CONVERSION["Delhi NSF LCC",METHOD["Lambert Conic Conformal (2SP)",ID["EPSG",9802]],PARAMETER["Latitude of false origin",28.62510126,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8821]],PARAMETER["Longitude of false origin",77,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8822]],PARAMETER["Latitude of 1st standard parallel",28.375,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8823]],PARAMETER["Latitude of 2nd standard parallel",28.875,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8824]],PARAMETER["Easting at false origin",1000000,LENGTHUNIT["metre",1],ID["EPSG",8826]],PARAMETER["Northing at false origin",1000000,LENGTHUNIT["metre",1],ID["EPSG",8827]]],CS[Cartesian,2],AXIS["easting (X)",east,ORDER[1],LENGTHUNIT["metre",1]],AXIS["northing (Y)",north,ORDER[2],LENGTHUNIT["metre",1]],USAGE[SCOPE["NNRMS National Spatial Framework (NSF) state resource database of medium resolution earth observation imagery and mapping."],AREA["India - Delhi national capital territory."],BBOX[28.4,76.83,28.89,77.34]],ID["EPSG",7760]]

In [22]:
railway = spatial_index_utils.reproject_gdf(railway, epsg_code)

GeoDataFrame now has the following CRS:

PROJCRS["WGS 84 / Delhi",BASEGEOGCRS["WGS 84",ENSEMBLE["World Geodetic System 1984 ensemble",MEMBER["World Geodetic System 1984 (Transit)"],MEMBER["World Geodetic System 1984 (G730)"],MEMBER["World Geodetic System 1984 (G873)"],MEMBER["World Geodetic System 1984 (G1150)"],MEMBER["World Geodetic System 1984 (G1674)"],MEMBER["World Geodetic System 1984 (G1762)"],ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1]],ENSEMBLEACCURACY[2.0]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4326]],CONVERSION["Delhi NSF LCC",METHOD["Lambert Conic Conformal (2SP)",ID["EPSG",9802]],PARAMETER["Latitude of false origin",28.62510126,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8821]],PARAMETER["Longitude of false origin",77,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8822]],PARAMETER["Latitude of 1st standard parallel",28.375,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8823]],PARAMETER["Latitude of 2nd standard parallel",28.875,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8824]],PARAMETER["Easting at false origin",1000000,LENGTHUNIT["metre",1],ID["EPSG",8826]],PARAMETER["Northing at false origin",1000000,LENGTHUNIT["metre",1],ID["EPSG",8827]]],CS[Cartesian,2],AXIS["easting (X)",east,ORDER[1],LENGTHUNIT["metre",1]],AXIS["northing (Y)",north,ORDER[2],LENGTHUNIT["metre",1]],USAGE[SCOPE["NNRMS National Spatial Framework (NSF) state resource database of medium resolution earth observation imagery and mapping."],AREA["India - Delhi national capital territory."],BBOX[28.4,76.83,28.89,77.34]],ID["EPSG",7760]]

In [23]:
colonies.crs == drain.crs == canal.crs == railway.crs

True

## Calculate Area (in square kilometers)

In [24]:
colonies['area_km2'] = colonies.area/1000000

In [25]:
colonies.head()

,index,AREA,USO_AREA_U,HOUSETAX_C,USO_FINAL,geometry,geom_type,area_km2
0,0,NEW DELHI 36,5584,None,Planned,"POLYGON Z ((1020282.788 996796.773 0.000, 1020...",<property object at 0x000001D82981F040>,1.966739
1,1,NEW DELHI 35,5585,None,Planned,"POLYGON Z ((1019724.475 994932.797 0.000, 1019...",<property object at 0x000001D82981F040>,0.036429
2,2,NEW DELHI 34,5586,None,Planned,"POLYGON Z ((1019571.955 994876.019 0.000, 1019...",<property object at 0x000001D82981F040>,0.230739
3,3,NEW DELHI 33,5587,None,Planned,"POLYGON Z ((1019352.702 994352.546 0.000, 1019...",<property object at 0x000001D82981F040>,0.281195
4,4,NEW DELHI 32,5588,None,Planned,"POLYGON Z ((1018793.292 994224.182 0.000, 1018...",<property object at 0x000001D82981F040>,0.301253

In [26]:
colonies['area_km2'].max()

29.116548965294925

In [27]:
colonies['area_km2'].min()

2.302821695521233e-09

## Compute barrier clip

In [28]:
colonies.head()

,index,AREA,USO_AREA_U,HOUSETAX_C,USO_FINAL,geometry,geom_type,area_km2
0,0,NEW DELHI 36,5584,None,Planned,"POLYGON Z ((1020282.788 996796.773 0.000, 1020...",<property object at 0x000001D82981F040>,1.966739
1,1,NEW DELHI 35,5585,None,Planned,"POLYGON Z ((1019724.475 994932.797 0.000, 1019...",<property object at 0x000001D82981F040>,0.036429
2,2,NEW DELHI 34,5586,None,Planned,"POLYGON Z ((1019571.955 994876.019 0.000, 1019...",<property object at 0x000001D82981F040>,0.230739
3,3,NEW DELHI 33,5587,None,Planned,"POLYGON Z ((1019352.702 994352.546 0.000, 1019...",<property object at 0x000001D82981F040>,0.281195
4,4,NEW DELHI 32,5588,None,Planned,"POLYGON Z ((1018793.292 994224.182 0.000, 1018...",<property object at 0x000001D82981F040>,0.301253

In [29]:
# Note... I had to reset index to make spatial join work!
#colonies = colonies.reset_index()
colonies = colonies.drop(columns=['index'])

In [30]:
colonies.head()

,AREA,USO_AREA_U,HOUSETAX_C,USO_FINAL,geometry,geom_type,area_km2
0,NEW DELHI 36,5584,None,Planned,"POLYGON Z ((1020282.788 996796.773 0.000, 1020...",<property object at 0x000001D82981F040>,1.966739
1,NEW DELHI 35,5585,None,Planned,"POLYGON Z ((1019724.475 994932.797 0.000, 1019...",<property object at 0x000001D82981F040>,0.036429
2,NEW DELHI 34,5586,None,Planned,"POLYGON Z ((1019571.955 994876.019 0.000, 1019...",<property object at 0x000001D82981F040>,0.230739
3,NEW DELHI 33,5587,None,Planned,"POLYGON Z ((1019352.702 994352.546 0.000, 1019...",<property object at 0x000001D82981F040>,0.281195
4,NEW DELHI 32,5588,None,Planned,"POLYGON Z ((1018793.292 994224.182 0.000, 1018...",<property object at 0x000001D82981F040>,0.301253

In [31]:
# Create new columns showing intersection with canal, railway and drain
colonies = spatial_index_utils.barrier_intersection(colonies, canal, "canal")

In [32]:
colonies = spatial_index_utils.barrier_intersection(colonies, railway, "railway")

In [33]:
colonies = spatial_index_utils.barrier_intersection(colonies, drain, "drain")

In [34]:
# Create barrier column as being intersection with canal, railway or drain
colonies['barrier'] = colonies['canal'] | colonies['railway'] | colonies["drain"]

In [35]:
colonies.head()

,AREA,USO_AREA_U,HOUSETAX_C,USO_FINAL,geometry,geom_type,area_km2,canal,railway,drain,barrier
0,NEW DELHI 36,5584,None,Planned,"POLYGON Z ((1020282.788 996796.773 0.000, 1020...",<property object at 0x000001D82981F040>,1.966739,False,True,False,True
1,NEW DELHI 35,5585,None,Planned,"POLYGON Z ((1019724.475 994932.797 0.000, 1019...",<property object at 0x000001D82981F040>,0.036429,False,False,False,False
2,NEW DELHI 34,5586,None,Planned,"POLYGON Z ((1019571.955 994876.019 0.000, 1019...",<property object at 0x000001D82981F040>,0.230739,False,False,False,False
3,NEW DELHI 33,5587,None,Planned,"POLYGON Z ((1019352.702 994352.546 0.000, 1019...",<property object at 0x000001D82981F040>,0.281195,False,False,False,False
4,NEW DELHI 32,5588,None,Planned,"POLYGON Z ((1018793.292 994224.182 0.000, 1018...",<property object at 0x000001D82981F040>,0.301253,False,False,False,False

In [36]:
len(colonies)

4357

## Calculate centroid for each polygon

In [37]:
colonies['centroid'] = colonies.centroid
colonies.head()

,AREA,USO_AREA_U,HOUSETAX_C,USO_FINAL,geometry,geom_type,area_km2,canal,railway,drain,barrier,centroid
0,NEW DELHI 36,5584,None,Planned,"POLYGON Z ((1020282.788 996796.773 0.000, 1020...",<property object at 0x000001D82981F040>,1.966739,False,True,False,True,POINT (1020123.175 995898.851)
1,NEW DELHI 35,5585,None,Planned,"POLYGON Z ((1019724.475 994932.797 0.000, 1019...",<property object at 0x000001D82981F040>,0.036429,False,False,False,False,POINT (1019673.024 994869.699)
2,NEW DELHI 34,5586,None,Planned,"POLYGON Z ((1019571.955 994876.019 0.000, 1019...",<property object at 0x000001D82981F040>,0.230739,False,False,False,False,POINT (1019485.484 994565.783)
3,NEW DELHI 33,5587,None,Planned,"POLYGON Z ((1019352.702 994352.546 0.000, 1019...",<property object at 0x000001D82981F040>,0.281195,False,False,False,False,POINT (1019171.868 994576.688)
4,NEW DELHI 32,5588,None,Planned,"POLYGON Z ((1018793.292 994224.182 0.000, 1018...",<property object at 0x000001D82981F040>,0.301253,False,False,False,False,POINT (1018785.675 994590.275)

## Distance from NDMC (turn into function)

In [38]:
# ndmc_center shapefile location
ndmc_center_filepath = os.path.join('shapefiles', 'ndmc_center7760.shp')

# Import shapefile
ndmc_center = gpd.read_file(ndmc_center_filepath)

# Extract NDMC Center as Shapely Point
ndmc_center_point = ndmc_center['geometry'].values[0]

# Code to generate ndmc_distances
# initialize new column with value 0
colonies['ndmc_dist_km'] = 0

# Compute distance from NDMC to centroid of each polygon
# Division by 1000 turns units into kilometers
for idx, row in colonies.iterrows():
    colonies.loc[idx, 'ndmc_dist_km'] = ndmc_center_point.distance(row['centroid'])/1000
    
colonies.head()

,AREA,USO_AREA_U,HOUSETAX_C,USO_FINAL,geometry,geom_type,area_km2,canal,railway,drain,barrier,centroid,ndmc_dist_km
0,NEW DELHI 36,5584,None,Planned,"POLYGON Z ((1020282.788 996796.773 0.000, 1020...",<property object at 0x000001D82981F040>,1.966739,False,True,False,True,POINT (1020123.175 995898.851),5.159809
1,NEW DELHI 35,5585,None,Planned,"POLYGON Z ((1019724.475 994932.797 0.000, 1019...",<property object at 0x000001D82981F040>,0.036429,False,False,False,False,POINT (1019673.024 994869.699),6.273149
2,NEW DELHI 34,5586,None,Planned,"POLYGON Z ((1019571.955 994876.019 0.000, 1019...",<property object at 0x000001D82981F040>,0.230739,False,False,False,False,POINT (1019485.484 994565.783),6.618792
3,NEW DELHI 33,5587,None,Planned,"POLYGON Z ((1019352.702 994352.546 0.000, 1019...",<property object at 0x000001D82981F040>,0.281195,False,False,False,False,POINT (1019171.868 994576.688),6.709542
4,NEW DELHI 32,5588,None,Planned,"POLYGON Z ((1018793.292 994224.182 0.000, 1018...",<property object at 0x000001D82981F040>,0.301253,False,False,False,False,POINT (1018785.675 994590.275),6.839299

## Create GeoDataFrame with Bounding Box of each Polygon

In [39]:
colonies_bbox = spatial_index_utils.create_bbox_gdf(colonies)

In [40]:
# To generate sindex
colonies_bbox_updated = gpd.GeoDataFrame(colonies_bbox, crs=colonies.crs)

## Spatial Join (intersection of polygon and bbox geometries)

In [41]:
colonies_bbox_nbrs = spatial_index_utils.add_polygon_neighbors_column_fast(polygon_gdf=colonies,
                                                       #right_gdf=colonies_bbox,
                                                       right_gdf = colonies_bbox_updated,
                                                       id_colname='USO_AREA_U', 
                                                       neighbor_colname='nbrs_bbox',
                                                       barrier_colname='barrier')
colonies_bbox_nbrs.head()

100%|██████████████████████████████████████████████████████████████████████████████| 4357/4357 [05:41<00:00, 12.74it/s]

,AREA,USO_AREA_U,HOUSETAX_C,USO_FINAL,geometry,geom_type,area_km2,canal,railway,drain,barrier,centroid,ndmc_dist_km,nbrs_bbox
0,NEW DELHI 36,5584,None,Planned,"POLYGON Z ((1020282.788 996796.773 0.000, 1020...",<property object at 0x000001D82981F040>,1.966739,False,True,False,True,POINT (1020123.175 995898.851),5.159809,"[5598, 5599, 5602, 5603, 3508, 3776, 4011, 349..."
1,NEW DELHI 35,5585,None,Planned,"POLYGON Z ((1019724.475 994932.797 0.000, 1019...",<property object at 0x000001D82981F040>,0.036429,False,False,False,False,POINT (1019673.024 994869.699),6.273149,"[5594, 5586]"
2,NEW DELHI 34,5586,None,Planned,"POLYGON Z ((1019571.955 994876.019 0.000, 1019...",<property object at 0x000001D82981F040>,0.230739,False,False,False,False,POINT (1019485.484 994565.783),6.618792,"[5594, 5587, 5585, 5596]"
3,NEW DELHI 33,5587,None,Planned,"POLYGON Z ((1019352.702 994352.546 0.000, 1019...",<property object at 0x000001D82981F040>,0.281195,False,False,False,False,POINT (1019171.868 994576.688),6.709542,"[5586, 5588, 5596]"
4,NEW DELHI 32,5588,None,Planned,"POLYGON Z ((1018793.292 994224.182 0.000, 1018...",<property object at 0x000001D82981F040>,0.301253,False,False,False,False,POINT (1018785.675 994590.275),6.839299,"[5621, 5587, 5620, 5596]"

## Calculate neighbor distances

In [42]:
colonies_bbox_nbrs = spatial_index_utils.calc_nbr_dist(polygon_gdf=colonies_bbox_nbrs,
                                  nbr_dist_colname='nbrs_dist_bbox',
                                  centroid_colname='centroid',
                                  neighbor_colname='nbrs_bbox',
                                  neighbor_id_col='USO_AREA_U')

colonies_bbox_nbrs.head()

100%|██████████████████████████████████████████████████████████████████████████████| 4357/4357 [04:06<00:00, 17.69it/s]

,AREA,USO_AREA_U,HOUSETAX_C,USO_FINAL,geometry,geom_type,area_km2,canal,railway,drain,barrier,centroid,ndmc_dist_km,nbrs_bbox,nbrs_dist_bbox
0,NEW DELHI 36,5584,None,Planned,"POLYGON Z ((1020282.788 996796.773 0.000, 1020...",<property object at 0x000001D82981F040>,1.966739,False,True,False,True,POINT (1020123.175 995898.851),5.159809,"[5598, 5599, 5602, 5603, 3508, 3776, 4011, 349...","[(5598, 1.0747903687722358), (5599, 1.01550641..."
1,NEW DELHI 35,5585,None,Planned,"POLYGON Z ((1019724.475 994932.797 0.000, 1019...",<property object at 0x000001D82981F040>,0.036429,False,False,False,False,POINT (1019673.024 994869.699),6.273149,"[5594, 5586]","[(5594, 0.6299162683015833), (5586, 0.35712228..."
2,NEW DELHI 34,5586,None,Planned,"POLYGON Z ((1019571.955 994876.019 0.000, 1019...",<property object at 0x000001D82981F040>,0.230739,False,False,False,False,POINT (1019485.484 994565.783),6.618792,"[5594, 5587, 5585, 5596]","[(5594, 0.4532645992827016), (5587, 0.31380549..."
3,NEW DELHI 33,5587,None,Planned,"POLYGON Z ((1019352.702 994352.546 0.000, 1019...",<property object at 0x000001D82981F040>,0.281195,False,False,False,False,POINT (1019171.868 994576.688),6.709542,"[5586, 5588, 5596]","[(5586, 0.3138054943362015), (5588, 0.38643264..."
4,NEW DELHI 32,5588,None,Planned,"POLYGON Z ((1018793.292 994224.182 0.000, 1018...",<property object at 0x000001D82981F040>,0.301253,False,False,False,False,POINT (1018785.675 994590.275),6.839299,"[5621, 5587, 5620, 5596]","[(5621, 0.5779093230805068), (5587, 0.38643264..."

## Create index column

In [43]:
colonies_bbox_nbrs['index'] = colonies_bbox_nbrs.index

In [44]:
colonies_bbox_nbrs.head()

,AREA,USO_AREA_U,HOUSETAX_C,USO_FINAL,geometry,geom_type,area_km2,canal,railway,drain,barrier,centroid,ndmc_dist_km,nbrs_bbox,nbrs_dist_bbox,index
0,NEW DELHI 36,5584,None,Planned,"POLYGON Z ((1020282.788 996796.773 0.000, 1020...",<property object at 0x000001D82981F040>,1.966739,False,True,False,True,POINT (1020123.175 995898.851),5.159809,"[5598, 5599, 5602, 5603, 3508, 3776, 4011, 349...","[(5598, 1.0747903687722358), (5599, 1.01550641...",0
1,NEW DELHI 35,5585,None,Planned,"POLYGON Z ((1019724.475 994932.797 0.000, 1019...",<property object at 0x000001D82981F040>,0.036429,False,False,False,False,POINT (1019673.024 994869.699),6.273149,"[5594, 5586]","[(5594, 0.6299162683015833), (5586, 0.35712228...",1
2,NEW DELHI 34,5586,None,Planned,"POLYGON Z ((1019571.955 994876.019 0.000, 1019...",<property object at 0x000001D82981F040>,0.230739,False,False,False,False,POINT (1019485.484 994565.783),6.618792,"[5594, 5587, 5585, 5596]","[(5594, 0.4532645992827016), (5587, 0.31380549...",2
3,NEW DELHI 33,5587,None,Planned,"POLYGON Z ((1019352.702 994352.546 0.000, 1019...",<property object at 0x000001D82981F040>,0.281195,False,False,False,False,POINT (1019171.868 994576.688),6.709542,"[5586, 5588, 5596]","[(5586, 0.3138054943362015), (5588, 0.38643264...",3
4,NEW DELHI 32,5588,None,Planned,"POLYGON Z ((1018793.292 994224.182 0.000, 1018...",<property object at 0x000001D82981F040>,0.301253,False,False,False,False,POINT (1018785.675 994590.275),6.839299,"[5621, 5587, 5620, 5596]","[(5621, 0.5779093230805068), (5587, 0.38643264...",4

## Remove extraneous columns (`geom_type`)

In [45]:
colonies_bbox_nbrs = colonies_bbox_nbrs.drop(columns=['geom_type'])

In [46]:
colonies_bbox_nbrs.head()

,AREA,USO_AREA_U,HOUSETAX_C,USO_FINAL,geometry,area_km2,canal,railway,drain,barrier,centroid,ndmc_dist_km,nbrs_bbox,nbrs_dist_bbox,index
0,NEW DELHI 36,5584,None,Planned,"POLYGON Z ((1020282.788 996796.773 0.000, 1020...",1.966739,False,True,False,True,POINT (1020123.175 995898.851),5.159809,"[5598, 5599, 5602, 5603, 3508, 3776, 4011, 349...","[(5598, 1.0747903687722358), (5599, 1.01550641...",0
1,NEW DELHI 35,5585,None,Planned,"POLYGON Z ((1019724.475 994932.797 0.000, 1019...",0.036429,False,False,False,False,POINT (1019673.024 994869.699),6.273149,"[5594, 5586]","[(5594, 0.6299162683015833), (5586, 0.35712228...",1
2,NEW DELHI 34,5586,None,Planned,"POLYGON Z ((1019571.955 994876.019 0.000, 1019...",0.230739,False,False,False,False,POINT (1019485.484 994565.783),6.618792,"[5594, 5587, 5585, 5596]","[(5594, 0.4532645992827016), (5587, 0.31380549...",2
3,NEW DELHI 33,5587,None,Planned,"POLYGON Z ((1019352.702 994352.546 0.000, 1019...",0.281195,False,False,False,False,POINT (1019171.868 994576.688),6.709542,"[5586, 5588, 5596]","[(5586, 0.3138054943362015), (5588, 0.38643264...",3
4,NEW DELHI 32,5588,None,Planned,"POLYGON Z ((1018793.292 994224.182 0.000, 1018...",0.301253,False,False,False,False,POINT (1018785.675 994590.275),6.839299,"[5621, 5587, 5620, 5596]","[(5621, 0.5779093230805068), (5587, 0.38643264...",4

## Save colonies file for Spatial Index

In [47]:
with open('colonies_bbox_nbrs6Sep2021.pkl', 'wb') as f:
    pickle.dump(colonies_bbox_nbrs, f)